### ISSUE TITLE
MySql support for .NET Core 3 will not be available until a compatible Pomelo library is released.

### ISSUE THREAD

**Issue by joeaudette** [cloudscribe/Announcements#12]
Releases of Pomelo.EntityFrameworkCore.MySql have tended to be slower than other providers. I think this is because it depends on the MySqlConnector from Oracle which is also slow to release updates for new versions of the framework.

This means that other EFCore providers will be updated to .NET Core 3 along with all cloudscribe code but it will not work with MySql until a compatible update of Pomelo is available.

The current problem is an error is thrown:

Method 'get_Info' in type 'Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal.MySqlOptionsExtension' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.MySqlServiceCollectionExtensions.AddEntityFrameworkMySql(IServiceCollection serviceCollection)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddCloudscribeCoreEFStorageMySql(IServiceCollection services, String connectionString, Boolean useSingletonLifetime, Int32 maxConnectionRetryCount, Int32 maxConnectionRetryDelaySeconds, ICollection`1 transientSqlErrorNumbersToAdd) in D:\_c\cloudscribe\src\cloudscribe.Core.Storage.EFCore.MySql\ServiceCollectionExtensions.cs:line 27
   at Microsoft.Extensions.DependencyInjection.CloudscribeFeatures.SetupDataStorage(IServiceCollection services, IConfiguration config, IWebHostEnvironment env) in D:\_c\cloudscribe\src\sourceDev.WebApp\Configuration\CloudscribeFeatures.cs:line 88
   at sourceDev.WebApp.Startup.ConfigureServices(IServiceCollection services) in D:\_c\cloudscribe\src\sourceDev.WebApp\Startup.cs:line 85
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at sourceDev.WebApp.Program.StartWebServer(String[] args) in D:\_c\cloudscribe\src\sourceDev.WebApp\Program.cs:line 59

**Comment by joeaudette** [comment]
This will pose a problem for releasing a new version of our project template because if we update it to create new projects for ASP.NET Core 3.0 then it will generate an app that does not work if the user chooses MySql.
We could possibly remove the MySql option temporarily.

**Comment by joeaudette** [comment]
turns out they released one
